name: authentication_via_handshake
version: 0.1.0
author: Paul Annekov <paul.annekov@gmail.com>
dependencies:
  cipher:
    git:
      url: git://github.com/izaera/cipher.git
      ref: devel
  collection: any
  args: any
